// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzz3S8dNBfNqBwxjU_JPcge55uGNGHboQ',
    appId: '1:223116581652:web:161e75bee0b2a8166c8001',
    messagingSenderId: '223116581652',
    projectId: 'cuberapp-b9e9a',
    authDomain: 'cuberapp-b9e9a.firebaseapp.com',
    storageBucket: 'cuberapp-b9e9a.firebasestorage.app',
    measurementId: 'G-P1BN9Y9G99',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyjW6WgJg8cXsr961rudQzMNzQyOvJMEQ',
    appId: '1:223116581652:android:48d65bf744f2aeab6c8001',
    messagingSenderId: '223116581652',
    projectId: 'cuberapp-b9e9a',
    storageBucket: 'cuberapp-b9e9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiA635VwXgkFZyDwoWmhddo-WS_z8uiOs',
    appId: '1:223116581652:ios:9f16c29ecb7a3eae6c8001',
    messagingSenderId: '223116581652',
    projectId: 'cuberapp-b9e9a',
    storageBucket: 'cuberapp-b9e9a.firebasestorage.app',
    iosBundleId: 'com.example.capp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiA635VwXgkFZyDwoWmhddo-WS_z8uiOs',
    appId: '1:223116581652:ios:9f16c29ecb7a3eae6c8001',
    messagingSenderId: '223116581652',
    projectId: 'cuberapp-b9e9a',
    storageBucket: 'cuberapp-b9e9a.firebasestorage.app',
    iosBundleId: 'com.example.capp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzz3S8dNBfNqBwxjU_JPcge55uGNGHboQ',
    appId: '1:223116581652:web:ac3c23c202709d2f6c8001',
    messagingSenderId: '223116581652',
    projectId: 'cuberapp-b9e9a',
    authDomain: 'cuberapp-b9e9a.firebaseapp.com',
    storageBucket: 'cuberapp-b9e9a.firebasestorage.app',
    measurementId: 'G-KY2GNEEPWC',
  );

}