// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfyN34RJhIYsHdFWr6T_w_sDN-m4vQ880',
    appId: '1:503578641265:web:9325b33c6c404a60a52cd0',
    messagingSenderId: '503578641265',
    projectId: 'catering-app-7d6e7',
    authDomain: 'catering-app-7d6e7.firebaseapp.com',
    storageBucket: 'catering-app-7d6e7.firebasestorage.app',
    measurementId: 'G-B8BMMN62Q5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDafbxx8GRSUQgZYOSSgkK0h5FjChzqzpw',
    appId: '1:503578641265:android:cea1847879c982c1a52cd0',
    messagingSenderId: '503578641265',
    projectId: 'catering-app-7d6e7',
    storageBucket: 'catering-app-7d6e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVg7SGYdSbraNwOanrAxUjIOF0cg3_I-Q',
    appId: '1:503578641265:ios:241e6c743a44a591a52cd0',
    messagingSenderId: '503578641265',
    projectId: 'catering-app-7d6e7',
    storageBucket: 'catering-app-7d6e7.firebasestorage.app',
    iosBundleId: 'com.example.capp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVg7SGYdSbraNwOanrAxUjIOF0cg3_I-Q',
    appId: '1:503578641265:ios:241e6c743a44a591a52cd0',
    messagingSenderId: '503578641265',
    projectId: 'catering-app-7d6e7',
    storageBucket: 'catering-app-7d6e7.firebasestorage.app',
    iosBundleId: 'com.example.capp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfyN34RJhIYsHdFWr6T_w_sDN-m4vQ880',
    appId: '1:503578641265:web:ea12547dd550e0e5a52cd0',
    messagingSenderId: '503578641265',
    projectId: 'catering-app-7d6e7',
    authDomain: 'catering-app-7d6e7.firebaseapp.com',
    storageBucket: 'catering-app-7d6e7.firebasestorage.app',
    measurementId: 'G-C5KG52PNEC',
  );
}
